In [ ]:
# creat 1d array
import numpy as np
arr=np.array ([1,2,3,45])
print(arr)



# 2D array of numpy

arr1=np.array ([[10,20,30,40],[22,44,66,77]])
print(arr1)


[ 1  2  3 45]
[[10 20 30 40]
 [22 44 66 77]]


In [6]:
arr1.itemsize  # total number
arr1.ndim

2

In [ ]:
print("The type of Arr1 is :",type(arr1))        #check datatype

The type of Arr1 is : <class 'numpy.ndarray'>


In [ ]:
import time 
size=11100000
py_list=list(range(size))
nump_arr=np.array(size)