In [2]:
# To print a numpy contain zero vector

import numpy as np
v=np.zeros(12)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
v[5]=1
print(v)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [22]:
#  creat a vector  with value ranging from 10 to 100

b=np.arange(10,19).reshape(3,3)
print(b) 

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [23]:
# To generate identity matrix

a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# creating a random matrix of 3*3*3
c=np.random.random((2,2,2,))
print(c)

[[[0.68170945 0.28462324]
  [0.10539188 0.47330385]]

 [[0.32533395 0.35177713]
  [0.20218451 0.31226275]]]


In [ ]:
# to creat a  4*4 array with  random value and find the max and minimum value
d=np.random.random((4,4))
print(d)
dmin,dmax= d.max() ,d.min()
print("The max & min valuw", dmin, dmax)

[[0.98886025 0.17604332 0.40346665 0.81845009]
 [0.81764152 0.67804639 0.10645835 0.84893222]
 [0.81698779 0.69973325 0.63512422 0.45936588]
 [0.73609961 0.02141468 0.79926135 0.24976912]]
The max & min valuw 0.9888602478383219 0.021414678733075565


In [37]:
# creat an array of 20 zero

arr = np.zeros(20)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# creat an array of 15 ones

arr = np.ones(15)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [46]:
# # creat an array of 10 five
import numpy as np
arr = np.full(10,5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [48]:
 # creat an array of all even  integer from 5 to 91

even=np.arange(5,91,2)
print(even) 

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89]


In [49]:
# creat a 7* identity matrix

matrix=np.eye(7,7)
print(matrix)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# generate a number of an array of 30 random sample from a standard 0-1

ram=np.random.normal(0,1,30)
print(ram)

[-0.92887318  0.36192963  2.25918655  0.11470535  0.49958658 -0.42797244
  0.3948299  -0.61838778  0.85735165 -0.89947703 -0.48829061 -0.51506777
 -1.92385455  0.59238794 -1.22315744 -1.41116705  0.95837707 -0.58295873
 -0.96059721 -0.45714337  0.10348201  0.90217179 -0.15211732  1.15938326
  1.92379041 -0.72802657  0.73136215  0.50497728 -0.41748408 -1.77021698]
